# -*- restclient -*-
#
POST http://localhost:8080/api/users
Content-Type: application/json

{
"name": "papo",
"email": "tomare"
}

# new waiter
#
POST http://localhost:8080/api/waiters
Content-Type: application/json

{
"first_name": "papo",
"last_name": "tomare",
"email": "tomareomo"
}
# new cashier
#
POST http://localhost:8080/api/cashiers
Content-Type: application/json

{
"first_name": "papo",
"last_name": "tomare",
"email": "tomareomo",
"admin": true
}
# new cashier
#
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "table": "6123456789abcdef0123456",
  "waiter": "abcdef012345678961234567",
  "foods": [
    "0123456789abcdef6123457",
    "abcdef901234567856123457"
  ],
  "drinks": [
    "1234567890abcdef7654321",
    "4567890abcdef1237654321"
  ],
  "status": "PENDING"
}
